fragment User on User {
  _id
  name
  display_name
  first_name
  last_name
  username
  description
  job_title
  company_name
  addresses {
    _id
    street_1
    street_2
    city
    region
    postal
    country
    title
    phone
    longitude
    latitude
    additional_directions
  }
  icebreakers {
    _id
    value
    question_expanded {
      _id
      title
    }
  }
  handle_facebook
  handle_instagram
  handle_linkedin
  handle_twitter
  handle_farcaster
  handle_github
  pronoun
  calendly_url
  website
  new_photos_expanded(limit: 1) {
    _id
    key
    bucket
  }
  url
  url_go
  lens_profile_synced

  followers
  following
  hosted
}

fragment PaymentAccount on NewPaymentAccount {
  _id
  provider
  type
  title
  account_info {
    ... on EthereumAccount {
      currencies
      currency_map
      address
      network
    }
    ... on SafeAccount {
      currencies
      currency_map
      address
      network
      owners
      threshold
      pending
    }
    ... on DigitalAccount {
      currencies
      currency_map
      account_id
    }
    ... on StripeAccount {
      currencies
      currency_map
      account_id
      publishable_key
    }
    ... on EthereumEscrowAccount {
      currencies
      currency_map
      address
      network
      minimum_deposit_percent
      host_refund_percent
      refund_policies {
        percent
        timestamp
      }
    }
    ... on EthereumRelayAccount {
      currencies
      currency_map
      address
      network
      payment_splitter_contract
    }
    ... on EthereumStakeAccount {
      currencies
      currency_map
      address
      network
      config_id
      requirement_checkin_before
    }
    ... on SolanaAccount {
      currencies
      currency_map
      address
      network
    }
  }
}

fragment AccountInfoFragment on AccountInfo {
  ... on EthereumAccount {
    currencies
    currency_map
    address
    network
  }
  ... on SafeAccount {
    currencies
    currency_map
    address
    network
    owners
    threshold
    pending
  }
  ... on DigitalAccount {
    currencies
    currency_map
    account_id
  }
  ... on StripeAccount {
    currencies
    currency_map
    account_id
    publishable_key
  }
  ... on EthereumEscrowAccount {
    currencies
    currency_map
    address
    network
    minimum_deposit_percent
    host_refund_percent
    refund_policies {
      percent
      timestamp
    }
  }
  ... on EthereumRelayAccount {
    currencies
    currency_map
    address
    network
    payment_splitter_contract
  }
  ... on EthereumStakeAccount {
    currencies
    currency_map
    address
    network
    config_id
    requirement_checkin_before
  }
  ... on SolanaAccount {
    currencies
    currency_map
    address
    network
  }
}
