query GetListLemonheadSponsors($wallet: String!) {
  listLemonheadSponsors(wallet: $wallet) {
    sponsors {
      limit
      sponsor {
        _id
        name
        image_url
        message
      }
      remaining
    }
  }
}

query CanMintLemonhead($wallet: String!) {
  canMintLemonhead(wallet: $wallet)
}
