query GetListLemonheadSponsors($wallet: String!) {
  listLemonheadSponsors(wallet: $wallet) {
    sponsors {
      limit
      sponsor {
        _id
        name
        image_url
        message
      }
      remaining
    }
  }
}

query CanMintLemonhead($wallet: String!) {
  canMintLemonhead(wallet: $wallet) {
    can_mint
    price
    white_list_enabled
  }
}

query GetListMyLemonheadInvitations {
  listMyLemonheadInvitations {
    invitations {
      invitee_wallet
      minted_at
      user {
        _id
        username
        image_avatar
      }
    }
  }
}

mutation SetUserWallet($token: String!, $signature: String!) {
  setUserWallet(token: $token, signature: $signature)
}

mutation UpdateMyLemonheadInvitations($invitations: [String!]!) {
  updateMyLemonheadInvitations(invitations: $invitations) {
    success
    message
    wallets
  }
}
