query listChains {
  listChains {
    active
    platform
    chain_id
    name
    code_name
    rpc_url
    block_explorer_url
    block_explorer_name
    block_explorer_for_tx
    block_explorer_for_token
    block_explorer_for_address
    block_explorer_icon_url
    block_time
    safe_confirmations
    logo_url
    tokens {
      active
      name
      symbol
      decimals
      contract
      logo_url
      is_native
    }
    access_registry_contract
    poap_contract
    marketplace_contract
    marketplace_version
    biconomy_api_key
    ens_registry
    proxy_admin_contract
    payment_config_registry_contract
    escrow_manager_contract
    relay_payment_contract
    stake_payment_contract
    reward_registry_contract
    eas_event_contract
    eas_graphql_url
    aragon_network
    axelar_chain_name
    donation_registry_contract
    lemonhead_contract_address
    lemonade_passport_contract_address
    zugrama_passport_contract_address
    poap_enabled
    launchpad_closed_permissions_contract_address
    launchpad_treasury_address_fee_split_manager_implementation_contract_address
    launchpad_treasury_staking_manager_implementation_contract_address
    launchpad_zap_contract_address
    launchpad_fee_escrow_contract_address
    launchpad_market_capped_price_contract_address
    launchpad_market_utils_contract_address
  }
}

query GetUserWalletRequest($wallet: String!) {
  getUserWalletRequest(wallet: $wallet) {
    message
    token
  }
}

mutation createFileUploads($uploadInfos: [FileUploadInfo!]!, $directory: String!) {
  createFileUploads(upload_infos: $uploadInfos, directory: $directory) {
    _id
    stamp
    state
    owner
    type
    size
    url
    bucket
    key
    presignedUrl: presigned_url
  }
}

query GetSelfVerificationStatus($config: SelfVerificationConfigInput!) {
  getSelfVerificationStatus(config: $config) {
    disclosures {
      type
      verified
    }
  }
}

mutation CreateSelfVerificationRequest($config: SelfVerificationConfigInput!) {
  createSelfVerificationRequest(config: $config) {
    endpoint
    endpoint_type
    scope
    uuid
  }
}
