mutation CreateOauth2Client($input: Oauth2ClientInput!) {
  createOauth2Client(input: $input) {
    client_id
    client_secret
    audience
  }
}

mutation UpdateOauth2Client($input: Oauth2ClientInput!, $updateOauth2ClientId: String!) {
  updateOauth2Client(input: $input, id: $updateOauth2ClientId) {
    client_id
  }
}

query ListOauth2Clients($ids: [String!]) {
  listOauth2Clients(ids: $ids) {
    client_id
    redirect_uris
  }
}
