fragment SectionLayoutFragment on SectionLayout {
  width
  padding
  columns
  alignment
  min_height
  background {
    type
    value
  }
}

fragment SectionDataBindingFragment on DataBinding {
  mode
  source {
    type
    field
  }
  overrides
}

fragment PageSectionFragment on PageSection {
  id
  type
  order
  hidden
  layout {
    ...SectionLayoutFragment
  }
  props
  data_binding {
    ...SectionDataBindingFragment
  }
  craft_node_id
  children {
    id
    type
    order
    hidden
    layout {
      ...SectionLayoutFragment
    }
    props
    data_binding {
      ...SectionDataBindingFragment
    }
    craft_node_id
    children {
      id
      type
      order
      hidden
      layout {
        ...SectionLayoutFragment
      }
      props
      data_binding {
        ...SectionDataBindingFragment
      }
      craft_node_id
      children {
        id
        type
        order
        hidden
        layout {
          ...SectionLayoutFragment
        }
        props
        data_binding {
          ...SectionDataBindingFragment
        }
        craft_node_id
        children {
          id
          type
          order
          hidden
          layout {
            ...SectionLayoutFragment
          }
          props
          data_binding {
            ...SectionDataBindingFragment
          }
          craft_node_id
        }
      }
    }
  }
}

fragment PageConfigFragment on PageConfig {
  _id
  name
  description
  owner_id
  owner_type
  status
  version
  published_version
  thumbnail_url
  created_at
  created_by
  last_edited_by
  locked_at
  locked_by
  template_id
  template_version_installed
  space_id
  theme {
    type
    mode
    colors {
      accent
    }
    background {
      type
      value
    }
    fonts {
      title {
        family
      }
      body {
        family
      }
    }
    effects {
      type
      value
    }
    css_variables
  }
  custom_code {
    css
    head_html
    body_html
    scripts {
      src
      content
      strategy
    }
  }
  sections {
    ...PageSectionFragment
  }
}

query GetPageConfig($id: MongoID, $ownerType: PageConfigOwnerType, $ownerId: MongoID) {
  getPageConfig(_id: $id, owner_type: $ownerType, owner_id: $ownerId) {
    ...PageConfigFragment
  }
}

mutation CreatePageConfig($input: CreatePageConfigInput!) {
  createPageConfig(input: $input) {
    ...PageConfigFragment
  }
}

mutation UpdatePageConfig($id: MongoID!, $input: UpdatePageConfigInput!) {
  updatePageConfig(id: $id, input: $input) {
    ...PageConfigFragment
  }
}
