fragment Space on Space {
  _id
  title
  admins {
    _id
    image_avatar
  }
  description
  is_ambassador
  followed
  followers
  followers_count
  image_avatar
  image_avatar_expanded {
    _id
    bucket
    url
    type
    key
  }
  image_cover
  image_cover_expanded {
    _id
    bucket
    url
    type
    key
  }
  creator
  creator_expanded {
    _id
    name
    image_avatar
  }
  slug
  private
  listed_events
  website
  address {
    _id
    city
    country
    latitude
    longitude
    street_1
    street_2
    region
    title
  }
  handle_instagram
  handle_twitter
  handle_linkedin
  handle_youtube
  handle_tiktok
  personal
  theme_data
  sub_spaces
  lens_feed_id
  council_members {
    user {
      _id
      display_name
      username
      image_avatar
    }
    wallet
  }
  state
  nft_enabled
}

fragment SpaceTagFragment on SpaceTag {
  _id
  color
  space
  tag
  targets
  type
}

fragment SpaceEventRequestFragment on SpaceEventRequest {
  _id
  created_at
  space
  event
  state
  decided_at
  decided_by
}

#### Queries

query GetSpaces($with_my_spaces: Boolean, $with_public_spaces: Boolean, $roles: [SpaceRole!], $featured: Boolean) {
  listSpaces(
    with_my_spaces: $with_my_spaces
    with_public_spaces: $with_public_spaces
    roles: $roles
    featured: $featured
  ) {
    ...Space
  }
}

query GetSpace($id: MongoID, $slug: String, $hostname: String) {
  getSpace(_id: $id, slug: $slug, hostname: $hostname) {
    ...Space
  }
}

query GetSpaceEvents(
  $skip: Int
  $limit: Int
  $startFrom: DateTimeISO
  $startTo: DateTimeISO
  $space: MongoID
  $sort: EventSortInput
  $endFrom: DateTimeISO
  $endTo: DateTimeISO
  $spaceTags: [MongoID!]
) {
  getEvents(
    skip: $skip
    limit: $limit
    start_from: $startFrom
    start_to: $startTo
    space: $space
    sort: $sort
    end_from: $endFrom
    end_to: $endTo
    space_tags: $spaceTags
  ) {
    _id
    shortid
    title
    host_expanded_new {
      _id
      image_avatar
      name
    }
    visible_cohosts_expanded_new {
      _id
      image_avatar
      name
    }
    address {
      city
      country
      region
      latitude
      longitude
    }
    new_new_photos_expanded {
      _id
      bucket
      key
      type
      url
    }
    published
    start
    end
    timezone
    external_url
    external_hostname
    event_ticket_types {
      _id
      prices {
        cost
        currency
        default
        payment_accounts
        payment_accounts_expanded {
          ...PaymentAccount
        }
      }
    }
    host_expanded_new {
      _id
      image_avatar
    }
    visible_cohosts_expanded_new {
      _id
      image_avatar
    }
  }
}

# NOTE: This will get all events of space to display on calendar
query GetSpaceEventsCalendar($space: MongoID) {
  getEvents(space: $space) {
    _id
    start
    address {
      _id
      latitude
      longitude
    }
  }
}

query GetSpaceTags($space: MongoID!) {
  listSpaceTags(space: $space) {
    ...SpaceTagFragment
  }
}

query GetSpaceEventRequests($space: MongoID!, $skip: Int!, $limit: Int!, $state: EventJoinRequestState) {
  getSpaceEventRequests(space: $space, skip: $skip, limit: $limit, state: $state) {
    records {
      _id
      created_at
      space
      event
      state
      decided_at
      decided_by
      created_by_expanded {
        name
        display_name
        email
      }
      event_expanded {
        title
        start
        timezone
        address {
          city
          country
          region
        }
        new_new_photos_expanded {
          _id
          bucket
          key
          type
          url
        }
        guests
      }
    }
    total
  }
}

query GetMySpaceEventRequests($space: MongoID!, $skip: Int!, $limit: Int!, $state: EventJoinRequestState) {
  getMySpaceEventRequests(space: $space, skip: $skip, limit: $limit, state: $state) {
    records {
      _id
      state
      event_expanded {
        _id
        title
        new_new_photos_expanded {
          key
          bucket
          _id
          url
          type
        }
      }
    }
  }
}

query getSubSpaces($id: MongoID!) {
  getSubSpaces(_id: $id) {
    _id
    title
    description
    followers_count
    slug
    is_admin
    followed
    image_avatar_expanded {
      _id
      bucket
      url
      type
      key
    }
  }
}

query GetListSpaceCategories {
  listSpaceCategories {
    description
    image_url
    listed_events_count
    space
    title
  }
}

query GetListGeoRegions {
  listGeoRegions {
    _id
    title
    cities {
      name
      region
      space
      icon_url
      listed_events_count
    }
  }
}

query CheckSpaceSlug($slug: String!) {
  canUseSpaceSlug(slug: $slug)
}

query SearchSpaces($skip: Int, $limit: Int, $input: SearchSpaceInput) {
  searchSpaces(input: $input, limit: $limit, skip: $skip) {
    items {
      ...Space
    }
    total
  }
}

query GetSpaceMembers(
  $space: MongoID!
  $roles: [SpaceRole!]
  $state: SpaceMembershipState
  $visible: Boolean
  $skip: Int
  $limit: Int
  $search: String
  $sort: SortInput
  $deletion: Boolean
  $tags: [MongoID!]
) {
  listSpaceMembers(
    space: $space
    roles: $roles
    state: $state
    visible: $visible
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    deletion: $deletion
    tags: $tags
  ) {
    total
    items {
      _id
      user
      user_name
      email
      space
      role
      state
      visible
      role_changed_at
      deleted_at
      user_expanded {
        _id
        name
        display_name
        email
        new_photos_expanded(limit: 1) {
          _id
          key
          bucket
        }
      }
      event_count
      checkin_count
      tags {
        _id
        space
        tag
        color
        type
        targets
        targets_count
      }
    }
  }
}

#### Mutations

mutation FollowSpace($space: MongoID!) {
  followSpace(space: $space)
}

mutation UnfollowSpace($space: MongoID!) {
  unfollowSpace(space: $space)
}

mutation UpdateSpace($id: MongoID!, $input: SpaceInput!) {
  updateSpace(_id: $id, input: $input) {
    ...Space
  }
}

mutation PinEventsToSpace($space: MongoID!, $events: [MongoID!]!, $tags: [MongoID!]) {
  pinEventsToSpace(space: $space, events: $events, tags: $tags) {
    requests {
      ...SpaceEventRequestFragment
    }
  }
}

# NOTE: ONLY NEED _id -> call PinEventsToSpace
mutation CreateExternalEvent($input: EventInput!) {
  createEvent(input: $input) {
    _id
  }
}

mutation CreateSpace($input: SpaceInput!) {
  createSpace(input: $input) {
    ...Space
  }
}

mutation DecideSpaceEventRequests($input: DecideSpaceEventRequestsInput!) {
  decideSpaceEventRequests(input: $input)
}

mutation AddSpaceMembers($input: AddSpaceMemberInput!) {
  addSpaceMembers(input: $input)
}

mutation DeleteSpaceMembers($input: DeleteSpaceMemberInput!) {
  deleteSpaceMembers(input: $input) {
    _id
    role
    state
    user
    user_name
    email
    deleted_at
    role_changed_at
    user_expanded {
      _id
      name
      email
      image_avatar
    }
    visible
  }
}

mutation DeleteSpace($id: MongoID!) {
  deleteSpace(_id: $id)
}

mutation UpsertSpaceTag($input: SpaceTagInput!) {
  insertSpaceTag(input: $input) {
    ...SpaceTagFragment
  }
}

mutation ManageSpaceTag($tagged: Boolean!, $target: String!, $id: MongoID!, $space: MongoID!) {
  manageSpaceTag(tagged: $tagged, target: $target, _id: $id, space: $space)
}

mutation DeleteSpaceTag($id: MongoID!, $space: MongoID!) {
  deleteSpaceTag(_id: $id, space: $space)
}

mutation AttachSubSpaces($id: MongoID!, $subSpaces: [String!]!) {
  attachSubSpaces(_id: $id, sub_spaces: $subSpaces)
}

mutation RemoveSubSpaces($subSpaces: [MongoID!]!, $id: MongoID!) {
  removeSubSpaces(sub_spaces: $subSpaces, _id: $id)
}

mutation UpdateSubSpaceOrder($id: MongoID!, $subSpaces: [MongoID!]!) {
  updateSubSpaceOrder(_id: $id, sub_spaces: $subSpaces)
}

mutation UpsertSpaceTag($input: SpaceTagInput!) {
  insertSpaceTag(input: $input) {
    ...SpaceTagFragment
  }
}

mutation DeleteSpaceTag($id: MongoID!, $space: MongoID!) {
  deleteSpaceTag(_id: $id, space: $space)
}

query GetSpaceNFTs($skip: Int, $limit: Int, $space: MongoID, $kind: SpaceNFTKind) {
  listSpaceNFTs(space: $space, limit: $limit, skip: $skip, kind: $kind) {
    items {
      _id
      cover_image_url
      name
      content_url
      kind
      token_limit
      contracts {
        _id
        space_nft
        network_id
        mint_price
        currency_address
      }
    }
    total
  }
}
