#### Queries

query GetSpaceSubscription($space: MongoID!) {
  getSpaceSubscription(space: $space) {
    subscription {
      _id
      cancel_at_period_end
      created_at
      current_period_end
      current_period_start
      status
      space
    }
    items {
      active
      type
    }
    payment {
      client_secret
      publishable_key
    }
  }
}

query ListSubscriptionItems {
  listSubscriptionItems {
    title
    type
    pricing {
      currency
      decimals
      price
      annual_price
    }
    weekly_email_limit
    credits_per_month
    crypto_prices {
      chain_id
      token_address
      amount
      amount_annual
    }
  }
}

query ListSubscriptionFeatureConfigs {
  listSubscriptionFeatureConfigs {
    feature_code
    feature_type
    display_label
    description
    tiers
  }
}

query PreviewUpdateSpaceSubscription($id: MongoID!, $space: MongoID!, $input: UpdateSubscriptionInput!) {
  previewUpdateSubscription(_id: $id, space: $space, input: $input) {
    price
    currency
    decimals
  }
}

#### Mutations

mutation CreateSpaceSubscription($input: CreateSubscriptionInput!) {
  createSpaceSubscription(input: $input) {
    subscription {
      _id
      status
      current_period_end
      current_period_start
      space
    }
    items {
      active
      type
    }
    payment {
      client_secret
      publishable_key
    }
  }
}

mutation UpdateSpaceSubscription($id: MongoID!, $space: MongoID!, $input: UpdateSubscriptionInput!) {
  updateSpaceSubscription(_id: $id, space: $space, input: $input) {
    subscription {
      _id
      status
      current_period_end
      current_period_start
      space
    }
    items {
      active
      type
    }
    payment {
      client_secret
      publishable_key
    }
  }
}

mutation CancelSpaceSubscription($id: MongoID!, $space: MongoID!) {
  cancelSpaceSubscription(_id: $id, space: $space)
}

mutation CreateCryptoSubscription($input: CreateCryptoSubscriptionInput!) {
  createCryptoSubscription(input: $input) {
    subscription_id
    forwarder_contract
    destination
    reference
    amount
    token_address
    chain_id
  }
}

mutation RenewCryptoSubscription($subscriptionId: MongoID!, $chainId: String!, $tokenAddress: String!, $annual: Boolean) {
  renewCryptoSubscription(subscription_id: $subscriptionId, chain_id: $chainId, token_address: $tokenAddress, annual: $annual) {
    subscription_id
    forwarder_contract
    destination
    reference
    amount
    token_address
    chain_id
  }
}

query GetCryptoSubscriptionStatus($subscriptionId: MongoID!) {
  getCryptoSubscriptionStatus(subscription_id: $subscriptionId) {
    subscription {
      _id
      status
      current_period_end
      current_period_start
      space
      payment_method
    }
    items {
      active
      type
    }
  }
}

subscription CryptoSubscriptionActivated($subscriptionId: MongoID!) {
  cryptoSubscriptionActivated(subscription_id: $subscriptionId) {
    subscription {
      _id
      status
      current_period_end
      current_period_start
      space
      payment_method
    }
    items {
      active
      type
    }
  }
}
