# Queries
query GetMe {
  getMe {
    ...User
    email
    email_verified
    wallets_new
    wallet_custodial
    stripe_connected_account {
      account_id
      connected
    }
    kratos_wallet_address
    kratos_farcaster_fid
    kratos_unicorn_wallet_address
    oauth2_allow_creation
    oauth2_clients
    oauth2_max_clients
  }
}

mutation SetUserWallet($token: String!, $signature: String!) {
  setUserWallet(token: $token, signature: $signature)
}

mutation UpdateUser($input: UserInput!) {
  updateUser(input: $input) {
    ...User
  }
}

query SearchUsers($query: String!) {
  searchUsers(query: $query) {
    _id
    email
    name
    display_name
    new_photos_expanded(limit: 1) {
      _id
      key
      bucket
    }
  }
}

query GetUser($id: MongoID, $username: String, $email: String, $lens_profile_id: String) {
  getUser(_id: $id, username: $username, email: $email, lens_profile_id: $lens_profile_id) {
    _id
    name
    display_name
    email
    username
    description
    followers
    following
    hosted
    addresses {
      _id
      street_1
      street_2
      city
      region
      postal
      country
      title
      phone
      longitude
      latitude
      additional_directions
    }
    new_photos_expanded(limit: 1) {
      _id
      key
      bucket
    }
    cover_expanded {
      _id
      bucket
      url
      type
      key
    }
    handle_facebook
    handle_instagram
    handle_linkedin
    handle_twitter
    handle_farcaster
    handle_github
    created_at
  }
}

mutation deleteUser {
  deleteUser
}

mutation syncUserUnicornWallet {
  syncUserUnicornWallet
}
