# Queries
query GetMe {
  getMe {
    ...User
    email
    wallets_new
    wallet_custodial
    email_verified
  }
}

mutation SetUserWallet($token: String!, $signature: String!) {
  setUserWallet(token: $token, signature: $signature)
}

mutation UpdateUser($input: UserInput!) {
  updateUser(input: $input) {
    ...User
  }
}
