# Queries
query GetMe {
  getMe {
    ...User
    email
    email_verified
    wallets_new
    wallet_custodial
    stripe_connected_account {
      account_id
      connected
    }
    kratos_wallet_address
  }
}

mutation SetUserWallet($token: String!, $signature: String!) {
  setUserWallet(token: $token, signature: $signature)
}

mutation UpdateUser($input: UserInput!) {
  updateUser(input: $input) {
    ...User
  }
}

query SearchUsers($query: String!) {
  searchUsers(query: $query) {
    _id
    email
    name
    display_name
    new_photos_expanded(limit: 1) {
      _id
      key
      bucket
    }
  }
}
