'use client';
import { useState } from 'react';
import { useAtomValue } from 'jotai';
import { useForm, Controller } from 'react-hook-form';

import { Button, Input, InputField, Menu, MenuItem, Segment, Toggle, toast, ErrorText, modal } from '$lib/components/core';
import { Pane } from '$lib/components/core/pane/pane';
import { chainsMapAtom, listChainsAtom } from '$lib/jotai';
import { useAppKitAccount } from '$lib/utils/appkit';
import { CreateGroupParams, SECONDS_PER_MONTH } from '$lib/services/token-launch-pad';
import { ConnectWallet } from '$lib/components/features/modals/ConnectWallet';
import { CreateGroupModal } from '$lib/components/features/community-manage/modals/CreateGroupModal';

type ActivateLaunchpadForm = {
  coinAddress: string;
  access: 'open' | 'closed';
  ownerFeeEnabled: boolean;
  ownerFee: number;
  coinCreatorsFee: number;
  membersFee: number;
  stakeDurationValue: number;
};

export function ActivateLaunchpad() {
  const chainsMap = useAtomValue(chainsMapAtom);
  const listChains = useAtomValue(listChainsAtom);
  const availableChains = listChains.filter(chain => chain.launchpad_zap_contract_address);
  const [selectedChainId, setSelectedChainId] = useState<string>(availableChains[0]?.chain_id || '');
  const launchChain = chainsMap[selectedChainId];
  const { register, setValue, watch, control, handleSubmit, formState: { errors } } = useForm<ActivateLaunchpadForm>({
    defaultValues: {
      coinAddress: '',
      access: 'open',
      ownerFeeEnabled: false,
      ownerFee: 0,
      coinCreatorsFee: 60,
      membersFee: 40,
      stakeDurationValue: 12,
    },
  });
  const { address } = useAppKitAccount();
  const access = watch('access');
  const ownerFeeEnabled = watch('ownerFeeEnabled');
  const ownerFee = watch('ownerFee');
  const coinCreatorsFee = watch('coinCreatorsFee');
  const membersFee = watch('membersFee');
  const [isEditingFees, setIsEditingFees] = useState(false);

  const clamp = (value: number) => Math.max(0, Math.min(100, value || 0));
  const ownerWidth = clamp(ownerFee);
  const creatorsWidth = clamp(coinCreatorsFee);
  const membersWidth = clamp(membersFee);
  const widthTotal = ownerWidth + creatorsWidth + membersWidth || 1;
  const ownerDisplayWidth = ownerWidth ? (ownerWidth / widthTotal) * 100 : 0;
  const creatorsDisplayWidth = creatorsWidth ? (creatorsWidth / widthTotal) * 100 : 0;
  const membersDisplayWidth = membersWidth ? (membersWidth / widthTotal) * 100 : 0;

  const handleActivate = handleSubmit((formData) => {
    if (!launchChain) {
      toast.error('Select a network before activating your launchpad');
      return;
    }

    const openCreateGroup = () => {
      if (!address) {
        toast.error('Connect your wallet to activate your launchpad');
        return;
      }

      const payload: CreateGroupParams = {
        groupERC20Token: formData.coinAddress,
        groupOwner: address,
        minEscrowDuration: 0,
        minStakeDuration: formData.stakeDurationValue * SECONDS_PER_MONTH,
        creatorSharePercentage: formData.coinCreatorsFee,
        ownerSharePercentage: formData.ownerFeeEnabled ? formData.ownerFee : 0,
        isOpen: formData.access === 'open',
      };

      modal.open(CreateGroupModal, {
        props: {
          params: payload,
          launchChain,
        },
      });
    };

    modal.open(ConnectWallet, {
      props: {
        chain: launchChain,
        onConnect: async () => {
          modal.close();
          openCreateGroup();
        },
      },
    });
  });

  return (
    <Pane.Root>
      <Pane.Header.Root>
        <Pane.Header.Left />
      </Pane.Header.Root>
      <Pane.Content className="p-4 flex flex-col gap-5">
        <div className="flex flex-col gap-4">
          <div className="size-[56px] flex items-center justify-center bg-primary/8 rounded-full">
            <i className="icon-rocket size-8 text-tertiary" />
          </div>
          <div>
            <h1 className="text-xl font-semibold">Activate Launchpad</h1>
            <p className="text-secondary">Set up your community coin, membership rules & trading fee split.</p>
          </div>
          <div className="space-y-2">
            <p className="text-lg">Community Coin</p>
            <ul className="list-disc pl-5.5 text-sm">
              <li className="text-sm font-medium text-secondary">Community Coins can be any ERC20 including Flaunch, Zora, Clanker coins.</li>
              <li className="text-sm font-medium text-secondary">Communities earn ETH from all of their subcoin trading fees.</li>
              <li className="text-sm font-medium text-secondary">Holders of the Community Coin receive pro-rata ETH from all rewards generated by the Community.</li>
            </ul>
          </div>
        </div>

        <div className="flex flex-col gap-1.5">
          <p className="text-sm">Network</p>
          <Menu.Root>
            <Menu.Trigger>
              <div className="flex items-center gap-3 py-2 px-3 rounded-sm border border-card-border bg-card cursor-pointer">
                {launchChain?.logo_url && (
                  <img src={launchChain.logo_url} alt={launchChain.name} className="size-5 rounded-full" />
                )}
                <p className="flex-1 text-left">{launchChain?.name || 'Select Network'}</p>
                <i className="icon-chevron-down text-tertiary size-4" />
              </div>
            </Menu.Trigger>
            <Menu.Content className="p-1 w-full">
              {({ toggle }) => (
                <>
                  {availableChains.map(chain => (
                    <MenuItem
                      key={chain.chain_id}
                      onClick={() => {
                        setSelectedChainId(chain.chain_id);
                        toggle();
                      }}
                    >
                      <div className="flex items-center gap-2.5 flex-1">
                        {chain.logo_url && (
                          <img src={chain.logo_url} alt={chain.name} className="size-4 rounded-full" />
                        )}
                        <p className="text-sm text-secondary flex-1">{chain.name}</p>
                        {selectedChainId === chain.chain_id && (
                          <i className="icon-check text-accent-400 size-4" />
                        )}
                      </div>
                    </MenuItem>
                  ))}
                </>
              )}
            </Menu.Content>
          </Menu.Root>
        </div>


        <div className="flex flex-col gap-1.5">
          <p className="text-sm">Coin Contract Address</p>
          <Input
            placeholder="0x000000..."
            {...register('coinAddress', { required: 'Coin Contract Address is required' })}
            variant="outlined"
            error={Boolean(errors.coinAddress)}
          />
          {errors.coinAddress?.message && <ErrorText message={errors.coinAddress.message} />}
          <p className="text-sm text-tertiary mt-0.5">This coin can be staked to earn the Group's ETH rewards.</p>
        </div>

        <div className="flex flex-col gap-1.5">
          <p className="text-sm">Access</p>
          <Segment
            selected={access}
            items={[
              { label: 'Open', value: 'open' },
              { label: 'Closed', value: 'closed' },
            ]}
            onSelect={(item) => {
              setValue('access', item.value as 'open' | 'closed');
            }}
          />
          <p className="text-sm text-tertiary mt-0.5">
            {access === 'open' ? 'Anyone can join and add subcoins.' : 'Only the creator can add subcoins.'}
          </p>
        </div>

        <hr className="border-t border-t-divider" />

        <div className="flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <p className="text-lg">Trading Fees</p>
            <Button
              variant="tertiary"
              size="sm"
              iconLeft={!isEditingFees ? 'icon-edit-sharp' : undefined}
              onClick={() => setIsEditingFees(!isEditingFees)}
            >
              {isEditingFees ? 'Save' : 'Edit'}
            </Button>
          </div>

          <div className="rounded-md bg-card flex items-center justify-between p-4">
            <div className="flex items-center gap-3">
              <i className="icon-attach-money text-tertiary size-5" />
              <div>
                <p className="text-sm font-medium">Community Owner Fee</p>
                <p className="text-sm text-tertiary">As Community Owner you can take a fee on all activity</p>
              </div>
            </div>
            <Toggle
              id="owner-fee-toggle"
              checked={ownerFeeEnabled}
              onChange={(value) => {
                setValue('ownerFeeEnabled', value);
                if (!value) {
                  setValue('ownerFee', 0);
                }
              }}
            />
          </div>

          {isEditingFees ? (
            <div className="space-y-3">
              <div className="space-y-1.5">
                <p className="text-sm text-secondary">Community Owner</p>
                <Controller
                  control={control}
                  name="ownerFee"
                  render={({ field }) => (
                    <div className="relative">
                      <Input
                        type="number"
                        variant="outlined"
                        value={field.value}
                        onChange={(event) => field.onChange(Number(event.target.value) || 0)}
                        min={0}
                        max={100}
                        disabled={!ownerFeeEnabled}
                      />
                      <span className="absolute inset-y-0 right-0 flex items-center pr-3 text-sm text-tertiary">%</span>
                    </div>
                  )}
                />
              </div>

              <div className="space-y-1.5">
                <p className="text-sm text-secondary">Coin Creators</p>
                <Controller
                  control={control}
                  name="coinCreatorsFee"
                  render={({ field }) => (
                    <div className="relative">
                      <Input
                        type="number"
                        variant="outlined"
                        value={field.value}
                        onChange={(event) => field.onChange(Number(event.target.value) || 0)}
                        min={0}
                        max={100}
                      />
                      <span className="absolute inset-y-0 right-0 flex items-center pr-3 text-sm text-tertiary">%</span>
                    </div>
                  )}
                />
              </div>

              <div className="space-y-1.5">
                <p className="text-sm text-secondary">Members</p>
                <Controller
                  control={control}
                  name="membersFee"
                  render={({ field }) => (
                    <div className="relative">
                      <Input
                        type="number"
                        variant="outlined"
                        value={field.value}
                        onChange={(event) => field.onChange(Number(event.target.value) || 0)}
                        min={0}
                        max={100}
                      />
                      <span className="absolute inset-y-0 right-0 flex items-center pr-3 text-sm text-tertiary">%</span>
                    </div>
                  )}
                />
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="flex w-full h-2 rounded-full overflow-hidden bg-card-border gap-0.5">
                {ownerDisplayWidth > 0 && (
                  <div
                    className="h-full bg-accent-400"
                    style={{ width: `${ownerDisplayWidth}%` }}
                  />
                )}
                {creatorsDisplayWidth > 0 && (
                  <div
                    className="h-full bg-alert-400"
                    style={{ width: `${creatorsDisplayWidth}%` }}
                  />
                )}
                {membersDisplayWidth > 0 && (
                  <div
                    className="h-full bg-warning-300"
                    style={{ width: `${membersDisplayWidth}%` }}
                  />
                )}
              </div>
              <div className="flex flex-wrap gap-4 text-sm">
                {ownerFee > 0 && (
                  <div className="flex items-center gap-1 text-secondary">
                    <span className="inline-block size-2 rounded-full bg-accent-400" />
                    <p className="text-accent-400 text-sm">Community Owner {ownerFee}%</p>
                  </div>
                )}
                <div className="flex items-center gap-1 text-secondary">
                  <span className="inline-block size-2 rounded-full bg-alert-400" />
                  <p className="text-alert-400 text-sm">Coin Creators {coinCreatorsFee}%</p>
                </div>
                <div className="flex items-center gap-1 text-secondary ">
                  <span className="inline-block size-2 rounded-full bg-warning-300" />
                  <p className="text-warning-300 text-sm">Members {membersFee}%</p>
                </div>
              </div>
            </div>
          )}
        </div>

        <hr className="border-t border-t-divider" />

        <div className="flex flex-col gap-4">
          <p className="text-lg">Membership Settings</p>
          <div className="flex gap-4 justify-between">
            <div>
              <p>Minimum Stake Duration</p>
              <p className="text-sm text-tertiary">Choose how long the coins stay locked for</p>
            </div>
            <div className="flex items-center justify-end">
              <Controller
                control={control}
                name="stakeDurationValue"
                render={({ field }) => (
                  <InputField
                    type="number"
                    value={String(field.value)}
                    onChangeText={(value) => {
                      const nextValue = Math.max(1, Number(value) || 1);
                      field.onChange(nextValue);
                    }}
                    subfix="months"
                    className="w-40"
                  />
                )}
              />
            </div>
          </div>
        </div>
      </Pane.Content>

      <Pane.Footer className="p-4 border-t border-t-divider">
        <Button
          variant="secondary"
          onClick={handleActivate}
        >
          Activate Launchpad
        </Button>
      </Pane.Footer>
    </Pane.Root>
  );
}
