import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import localFont from 'next/font/local';

import StyledJsxRegistry from './registry';
import './globals.css';
import clsx from 'clsx';

const classDisplay = localFont({ src: '../public/fonts/ClashDisplay-Variable.ttf' });
const generalSans = localFont({ src: '../public/fonts/GeneralSans-Variable.ttf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme');

  return (
    <html lang="en" color-scheme={theme?.value}>
      <body className={clsx('transition antialiased overflow-hidden', classDisplay.className, generalSans.className)}>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
