import { format } from 'date-fns';
import { tz } from '@date-fns/tz';

export type TimezoneOption = {
  value: string;
  text: string;
  short: string;
};

const TIMEZONES = {
  'Pacific/Midway': 'Midway Island, Samoa',
  'Pacific/Honolulu': 'Hawaii',
  'US/Alaska': 'Alaska',
  'America/Los_Angeles': 'Pacific Time (US & Canada)',
  'America/Tijuana': 'Tijuana, Baja California',
  'US/Arizona': 'Arizona',
  'America/Chihuahua': 'Chihuahua, La Paz, Mazatlan',
  'US/Mountain': 'Mountain Time (US & Canada)',
  'America/Managua': 'Central America',
  'US/Central': 'Central Time (US & Canada)',
  'America/Mexico_City': 'Guadalajara, Mexico City, Monterrey',
  'Canada/Saskatchewan': 'Saskatchewan',
  'America/Bogota': 'Bogota, Lima, Quito, Rio Branco',
  'US/Eastern': 'Eastern Time (US & Canada)',
  'US/East-Indiana': 'Indiana (East)',
  'Canada/Atlantic': 'Atlantic Time (Canada)',
  'America/Caracas': 'Caracas, La Paz',
  'America/Manaus': 'Manaus',
  'America/Santiago': 'Santiago',
  'Canada/Newfoundland': 'Newfoundland',
  'America/Sao_Paulo': 'Brasilia',
  'America/Argentina/Buenos_Aires': 'Buenos Aires, Georgetown',
  'America/Godthab': 'Greenland',
  'America/Montevideo': 'Montevideo',
  'America/Noronha': 'Mid-Atlantic',
  'Atlantic/Cape_Verde': 'Cape Verde Is.',
  'Atlantic/Azores': 'Azores',
  'Africa/Casablanca': 'Casablanca, Monrovia, Reykjavik',
  'Etc/Greenwich': 'Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',
  'Europe/Amsterdam': 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
  'Europe/Belgrade': 'Belgrade, Bratislava, Budapest, Ljubljana, Prague',
  'Europe/Brussels': 'Brussels, Copenhagen, Madrid, Paris',
  'Europe/Sarajevo': 'Sarajevo, Skopje, Warsaw, Zagreb',
  'Africa/Lagos': 'West Central Africa',
  'Asia/Amman': 'Amman',
  'Europe/Athens': 'Athens, Bucharest, Istanbul',
  'Asia/Beirut': 'Beirut',
  'Africa/Cairo': 'Cairo',
  'Africa/Harare': 'Harare, Pretoria',
  'Europe/Helsinki': 'Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
  'Asia/Jerusalem': 'Jerusalem',
  'Europe/Minsk': 'Minsk',
  'Africa/Windhoek': 'Windhoek',
  'Asia/Kuwait': 'Kuwait, Riyadh, Baghdad',
  'Europe/Moscow': 'Moscow, St. Petersburg, Volgograd',
  'Africa/Nairobi': 'Nairobi',
  'Asia/Tbilisi': 'Tbilisi',
  'Asia/Tehran': 'Tehran',
  'Asia/Muscat': 'Abu Dhabi, Muscat',
  'Asia/Baku': 'Baku',
  'Asia/Yerevan': 'Yerevan',
  'Asia/Kabul': 'Kabul',
  'Asia/Yekaterinburg': 'Yekaterinburg',
  'Asia/Karachi': 'Islamabad, Karachi, Tashkent',
  'Asia/Calcutta': 'Sri Jayawardenapura',
  'Asia/Katmandu': 'Kathmandu',
  'Asia/Almaty': 'Almaty, Novosibirsk',
  'Asia/Dhaka': 'Astana, Dhaka',
  'Asia/Rangoon': 'Yangon (Rangoon)',
  'Asia/Bangkok': 'Bangkok, Hanoi, Jakarta',
  'Asia/Krasnoyarsk': 'Krasnoyarsk',
  'Asia/Hong_Kong': 'Beijing, Chongqing, Hong Kong, Urumqi',
  'Asia/Kuala_Lumpur': 'Kuala Lumpur, Singapore',
  'Asia/Irkutsk': 'Irkutsk, Ulaan Bataar',
  'Australia/Perth': 'Perth',
  'Asia/Taipei': 'Taipei',
  'Asia/Tokyo': 'Osaka, Sapporo, Tokyo',
  'Asia/Seoul': 'Seoul',
  'Asia/Yakutsk': 'Yakutsk',
  'Australia/Adelaide': 'Adelaide',
  'Australia/Darwin': 'Darwin',
  'Australia/Brisbane': 'Brisbane',
  'Australia/Canberra': 'Canberra, Melbourne, Sydney',
  'Australia/Hobart': 'Hobart',
  'Pacific/Guam': 'Guam, Port Moresby',
  'Asia/Vladivostok': 'Vladivostok',
  'Asia/Magadan': 'Magadan, Solomon Is., New Caledonia',
  'Pacific/Auckland': 'Auckland, Wellington',
  'Pacific/Fiji': 'Fiji, Kamchatka, Marshall Is.',
  'Pacific/Tongatapu': "Nuku'alofa",
  'Pacific/Apia': 'Apia, Kiritimati',
  'Pacific/Niue': 'Niue',
  'Pacific/Rarotonga': 'Rarotonga',
  'Pacific/Tahiti': 'Tahiti',
  'Pacific/Marquesas': 'Marquesas',
  'Pacific/Gambier': 'Gambier',
  'Pacific/Pitcairn': 'Pitcairn',
  'America/Belize': 'Belize',
  'America/Costa_Rica': 'Costa Rica',
  'America/El_Salvador': 'El Salvador',
  'Pacific/Galapagos': 'Galapagos',
  'America/Guatemala': 'Guatemala',
  'America/Cancun': 'America Cancun',
  'Pacific/Easter': 'Easter Island',
  'America/Guayaquil': 'Guayaquil',
  'America/Havana': 'Havana',
  'America/Jamaica': 'Jamaica',
  'America/Lima': 'Lima',
  'America/Nassau': 'Nassau',
  'America/Panama': 'Panama',
  'America/Port-au-Prince': 'Port-au-Prince',
  'America/Rio_Branco': 'Rio Branco',
  'America/Barbados': 'Barbados',
  'Atlantic/Bermuda': 'Bermuda',
  'America/Boa_Vista': 'Boa Vista',
  'America/Curacao': 'Curacao',
  'America/Grand_Turk': 'Grand Turk',
  'America/Guyana': 'Guyana',
  'America/La_Paz': 'La Paz',
  'America/Martinique': 'Martinique',
  'America/Port_of_Spain': 'Port of Spain',
  'America/Porto_Velho': 'Porto Velho',
  'America/Puerto_Rico': 'Puerto Rico',
  'America/Santo_Domingo': 'Santo Domingo',
  'America/Thule': 'Thule',
  'America/St_Johns': 'Newfoundland Time - St. Johns',
  'America/Araguaina': 'Araguaina',
  'America/Asuncion': 'Asuncion',
  'America/Belem': 'Belem',
  'America/Campo_Grande': 'Campo Grande',
  'America/Cayenne': 'Cayenne',
  'America/Cuiaba': 'Cuiaba',
  'America/Fortaleza': 'Fortaleza',
  'America/Maceio': 'Maceio',
  'America/Miquelon': 'Miquelon',
  'Antarctica/Palmer': 'Palmer',
  'America/Paramaribo': 'Paramaribo',
  'America/Punta_Arenas': 'Punta Arenas',
  'America/Recife': 'Recife',
  'Antarctica/Rothera': 'Rothera',
  'America/Bahia': 'Salvador',
  'Atlantic/Stanley': 'Stanley',
  'Atlantic/South_Georgia': 'South Georgia',
  'America/Scoresbysund': 'Scoresbysund',
  'Africa/Abidjan': 'Abidjan',
  'Africa/Accra': 'Accra',
  'Africa/Bissau': 'Bissau',
  'Atlantic/Canary': 'Canary Islands',
  'America/Danmarkshavn': 'Danmarkshavn',
  'Europe/Dublin': 'Dublin',
  'Africa/El_Aaiun': 'El Aaiun',
  'Atlantic/Faroe': 'Faeroe',
  'Europe/Lisbon': 'Lisbon',
  'Europe/London': 'London',
  'Africa/Monrovia': 'Monrovia',
  'Atlantic/Reykjavik': 'Reykjavik',
  'Africa/Algiers': 'Algiers',
  'Europe/Andorra': 'Andorra',
  'Africa/Ceuta': 'Ceuta',
  'Europe/Gibraltar': 'Gibraltar',
  'Europe/Luxembourg': 'Luxembourg',
  'Europe/Malta': 'Malta',
  'Europe/Monaco': 'Monaco',
  'Africa/Ndjamena': 'Ndjamena',
  'Europe/Oslo': 'Oslo',
  'Europe/Tirane': 'Tirane',
  'Africa/Tunis': 'Tunis',
  'Europe/Zurich': 'Zurich',
  'Europe/Chisinau': 'Chisinau',
  'Asia/Damascus': 'Damascus',
  'Asia/Gaza': 'Gaza',
  'Africa/Johannesburg': 'Johannesburg',
  'Africa/Khartoum': 'Khartoum',
  'Europe/Kiev': 'Kiev',
  'Africa/Maputo': 'Maputo',
  'Europe/Kaliningrad': 'Moscow-01 - Kaliningrad',
  'Asia/Nicosia': 'Nicosia',
  'Europe/Riga': 'Riga',
  'Europe/Sofia': 'Sofia',
  'Europe/Tallinn': 'Tallinn',
  'Africa/Tripoli': 'Tripoli',
  'Europe/Vilnius': 'Vilnius',
  'Asia/Baghdad': 'Baghdad',
  'Europe/Istanbul': 'Istanbul',
  'Asia/Qatar': 'Qatar',
  'Asia/Riyadh': 'Riyadh',
  'Antarctica/Syowa': 'Syowa',
  'Asia/Dubai': 'Dubai',
  'Indian/Mahe': 'Mahe',
  'Indian/Mauritius': 'Mauritius',
  'Europe/Samara': 'Moscow+01 - Samara',
  'Indian/Reunion': 'Reunion',
  'Asia/Aqtau': 'Aqtau',
  'Asia/Aqtobe': 'Aqtobe',
  'Asia/Ashgabat': 'Ashgabat',
  'Asia/Dushanbe': 'Dushanbe',
  'Indian/Kerguelen': 'Kerguelen',
  'Indian/Maldives': 'Maldives',
  'Antarctica/Mawson': 'Mawson',
  'Asia/Colombo': 'Colombo',
  'Asia/Bishkek': 'Bishkek',
  'Indian/Chagos': 'Chagos',
  'Asia/Omsk': 'Moscow+03 - Omsk',
  'Asia/Thimphu': 'Thimphu',
  'Antarctica/Vostok': 'Vostok',
  'Indian/Cocos': 'Cocos',
  'Indian/Christmas': 'Christmas',
  'Antarctica/Davis': 'Davis',
  'Asia/Hovd': 'Hovd',
  'Asia/Brunei': 'Brunei',
  'Asia/Choibalsan': 'Choibalsan',
  'Asia/Makassar': 'Makassar',
  'Asia/Manila': 'Manila',
  'Asia/Dili': 'Dili',
  'Asia/Jayapura': 'Jayapura',
  'Pacific/Palau': 'Palau',
  'Antarctica/DumontDUrville': "Dumont D'Urville",
  'Pacific/Port_Moresby': 'Port Moresby',
  'Pacific/Chuuk': 'Truk',
  'Antarctica/Casey': 'Casey',
  'Australia/Sydney': 'Eastern Time - Melbourne, Sydney',
  'Pacific/Efate': 'Efate',
  'Pacific/Guadalcanal': 'Guadalcanal',
  'Pacific/Kosrae': 'Kosrae',
  'Pacific/Norfolk': 'Norfolk',
  'Pacific/Noumea': 'Noumea',
  'Pacific/Pohnpei': 'Ponape',
  'Pacific/Funafuti': 'Funafuti',
  'Pacific/Kwajalein': 'Kwajalein',
  'Pacific/Majuro': 'Majuro',
  'Pacific/Nauru': 'Nauru',
  'Pacific/Tarawa': 'Tarawa',
  'Pacific/Wake': 'Wake',
  'Pacific/Wallis': 'Wallis',
  'Pacific/Enderbury': 'Enderbury',
  'Pacific/Fakaofo': 'Fakaofo',
  'Pacific/Kiritimati': 'Kiritimati',
};

export const timezoneOptions = Object.entries(TIMEZONES).map(([key, value]) => {
  const zz = format(new Date(), 'OOOO', { in: tz(key) });
  return {
    value: key,
    text: `(${zz}) ${value}`,
    short: zz,
  };
});

export const getTimezoneOption = (timezone: string) => timezoneOptions.find((option) => option.value === timezone);

export const getUserTimezoneOption = (defaultTimezone?: string) => {
  if (defaultTimezone) return timezoneOptions.find((option) => option.value === defaultTimezone);

  const timezoneOffset = new Date().getTimezoneOffset();
  const sign = timezoneOffset < 0 ? '+' : '-';
  let minutes = Math.abs(timezoneOffset);
  const hours = Math.floor(minutes / 60);
  minutes = minutes - 60 * hours;
  const timezone = `GMT${sign}${('0' + hours).slice(-2)}:${('0' + minutes).slice(-2)}`;
  return timezoneOptions.find((option) => option.text.includes(timezone));
};
