query GetEvent($id: MongoID, $shortid: String) {
  getEvent(_id: $id, shortid: $shortid) {
    _id
    title
    description
    start
    shortid
    host_expanded {
      ...User
    }
    new_new_photos_expanded {
      _id
      stamp
      type
      url
      size
      bucket
      key
    }
    address {
      street_1
      city
      title
      region
      country
      additional_directions

      latitude
      longitude
    }
    address_directions

    sessions {
      _id
      start
      end
      broadcast
      description
      title
      broadcast
      photos_expanded {
        _id
        key
        bucket
      }
      speaker_users
      speaker_users_expanded {
        ...User
      }
    }
  }
}
