name: Deploy to Production
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  APP_ENV: production
  DOCKER_BUILDKIT: 1
  GITHUB_SHA: ${{ github.sha }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: lemonadesocial
  SENTRY_PROJECT: lemonade-web-new
  SENTRY_RELEASE: ${{ github.sha }}

jobs:
  buildAndPush:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.PRODUCTION_REGION }}
          role-to-assume: ${{ secrets.PRODUCTION_ROLE_TO_ASSUME }}

      - name: Generate .env file from GitHub variables
        run: |
          echo "NEXT_PUBLIC_ENABLE_WHITELABEL=${{ vars.PRODUCTION_NEXT_PUBLIC_ENABLE_WHITELABEL }}" >> .env
          echo "NEXT_PUBLIC_GRAPHQL_URL=${{ vars.PRODUCTION_NEXT_PUBLIC_GRAPHQL_URL }}" >> .env
          echo "NEXT_PUBLIC_AIRSTACK_URL=${{ vars.PRODUCTION_NEXT_PUBLIC_AIRSTACK_URL }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_MAP_KEY=${{ vars.PRODUCTION_NEXT_PUBLIC_GOOGLE_MAP_KEY }}" >> .env
          echo "NEXT_PUBLIC_LEMONADE_DOMAIN=${{ vars.PRODUCTION_NEXT_PUBLIC_LEMONADE_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_KRATOS_PUBLIC_URL=${{ vars.PRODUCTION_NEXT_PUBLIC_KRATOS_PUBLIC_URL }}" >> .env

      - name: Configure environment
        run: |
          aws ssm get-parameter --name ${{ secrets.PRODUCTION_PARAMETER_NAME }} | jq '.Parameter.Value' | jq '. | fromjson' | jq -r 'to_entries | .[] | .key + "=" + .value' >> $GITHUB_ENV || exit 1
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> .npmrc

      - name: Amazon ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Bake
        uses: docker/bake-action@v2
        with:
          targets: builder,nginx,upload,app
          set: |
            builder.cache-from=type=registry,ref=${{ env.REPOSITORY_URI }}:release-builder
            builder.cache-to=type=inline
            builder.tags=${{ env.REPOSITORY_URI }}:release-builder
            builder.output=type=registry
            nginx.tags=${{ env.REPOSITORY_URI }}:${{ env.GITHUB_SHA }}-nginx
            nginx.tags=${{ env.REPOSITORY_URI }}:release-nginx
            nginx.output=type=registry
            app.tags=${{ env.REPOSITORY_URI }}:${{ env.GITHUB_SHA }}-app
            app.tags=${{ env.REPOSITORY_URI }}:release-app
            app.output=type=registry

  deploy:
    needs: buildAndPush
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.PRODUCTION_REGION }}
          role-to-assume: ${{ secrets.PRODUCTION_ROLE_TO_ASSUME }}

      - name: Configure environment
        run: |
          aws ssm get-parameter --name ${{ secrets.PRODUCTION_PARAMETER_NAME }} | jq '.Parameter.Value' | jq '. | fromjson' | jq -r 'to_entries | .[] | .key + "=" + .value' >> $GITHUB_ENV || exit 1

      - name: Configure kube
        run: |
          eval $KUBECONFIG_COMMAND

      - name: Deploy
        run: |
          kubectl set image --namespace $NAMESPACE deployment/web-new web-new-app=$REPOSITORY_URI:$GITHUB_SHA-app web-new-nginx=$REPOSITORY_URI:$GITHUB_SHA-nginx

      - name: Verify
        run: |
          kubectl rollout status --namespace $NAMESPACE deployment/web-new
