name: Lint
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lemonadesocial'

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
